### ISSUE TITLE
Do not understand what to do with pin A0

### ISSUE THREAD

**Issue by nkkromhof** [mahowik/BalancingWii#1]
Hi mahowik,

I'm planning to build a BalancingWii robot with your code but I don't quite understand the wiring instructions...

What exactly do you mean by:
A0 - V_BATPIN: after the resistor divisor we should get [0V;5V]->[0;1023] on analogue V_BATPIN with R1=33k and R2=51k, i.e. (+12v)~51k~(A0 pin)~33k~(GND)

What am I supposed to do with A0, what does it get connected to?

Thanks in advance,
Niek

**Comment by mahowik** [comment]
V_BATPIN it's to control battery voltage level. It's not mandatory.

**Comment by nkkromhof** [comment]
Ahh okay, I will continue without it for now then, thanks for the quick answer and thanks for your work on this.
