### ISSUE TITLE
Bluetooth and custom Android  App

### ISSUE THREAD

**Issue by ss1996elcity** [mahowik/BalancingWii#13]
Good afternoon. I am writing my Android application to work with your library. Could you name the sequence of commands in order to bring the robot to working condition (analysis of the source code didn’t help much (((). Here I turned on the robot. Then, as I understand it, in the loop function in BalancingWii.cpp, the program parses Serial every time the port, and depending on the received command, performs some action. Could you, if it is not difficult for you, write a sequence of commands. For example: 1st action (robot is lying) - calibration. After that, you need to send the robot (and it should start balancing in some mode) and set the operation mode (send "this command"). the team must be commanded, and the team sent back - "the team goes back", turn left - "the team turn left by a certain number of degrees, the team turn right -" the team turn right by some amount of degrees ". If the robot crashes - change the operating mode to raise the robot - "command to change the operating mode of the robot to independently raise". and hereinafter referred to as the “raising team”. And then a sequence of commands to return to the normal operation of the robot. I really hope for your support.

**Comment by mahowik** [comment]
hi
This repository is based on modified MultiWii 2.3 project. But serial communication protocol was not changed at all.
So just google  about "MultiWii serial protocol" to deal with it.
https://github.com/mahowik/BalancingWii/blob/master/Protocol.cpp

p.s. Actually you need that because EZ-GUI app is ready to go ;)

**Comment by ss1996elcity** [comment]
Do you now how build this project in Android Studio now?

пн, 11 мая 2020 г., 22:00 Alexandr Arhutich <notifications@github.com>:

**Comment by mahowik** [comment]
no sorry

**Comment by ss1996elcity** [comment]
> no sorry

Thanks for your reply. Could you tell me, by what rule is it necessary to adjust the PID in your project? I cannot achieve a stable position for my robot. I have an accelerometer orientation - ROLL (if that helps).
