### ISSUE TITLE
How to tune the PID loop?

### ISSUE THREAD

**Issue by ss1996elcity** [mahowik/BalancingWii#14]
How to tune the PID loop?

**Comment by mahowik** [comment]
read how to tune multiwii pid but before read theory how tune pid in general

**Comment by ss1996elcity** [comment]
> read how to tune multiwii pid but before read theory how tune pid in general

We need tune Kp, Ki, Kd. If my orientation ROLL - this mean that i have to tune only ROLL_P, ROLL_I, ROLL_D. What about speed? Do I need something else in your project?
