### ISSUE TITLE
Pin change ?

### ISSUE THREAD

**Issue by ibrahimnadi** [mahowik/BalancingWii#15]
I want to use arduino uno cnc shield to build the robot. How do I change the default pins? Thank you

**Comment by mahowik** [comment]
please check arduino guides for this

**Comment by satpalsony** [comment]
Now I am busy with some other work, I will definitely take time to try and
thank you very much

**Comment by ibrahimnadi** [comment]
Nezaketiniz için çok teşekkür ederim.
