### ISSUE TITLE
Code won't compile

### ISSUE THREAD

**Issue by heisenberg550** [mahowik/BalancingWii#16]
Hello sir,,
thanks for your sharing your work. when i trying to verify the files by clicking the checkmark in the IDE in the top left corner, and check to make sure there are no errors displayed in the console at the bottom of the IDE. i keep getting this error 

`sketch\RX.cpp: In function 'computeRC()':
sketch\RX.cpp:435:26: warning: iteration 8 invokes undefined behavior [-Waggressive-loop-optimizations]
         if (rcSerial[chan] >900) {rcData[chan] = rcSerial[chan];} // only relevant channels are overridden
             ~~~~~~~~~~~~~^

sketch\RX.cpp:412:25: note: within this loop
     for (chan = 0; chan < RC_CHANS; chan++) {
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\main.cpp: In function 'main':
sketch\RX.cpp:435:26: warning: iteration 8 invokes undefined behavior [-Waggressive-loop-optimizations]
         if (rcSerial[chan] >900) {rcData[chan] = rcSerial[chan];} // only relevant channels are overridden
                          ^

sketch\RX.cpp:412:25: note: within this loop
     for (chan = 0; chan < RC_CHANS; chan++) {
                         ^

Sketch uses 14300 bytes (46%) of program storage space. Maximum is 30720 bytes.
Global variables use 1022 bytes (49%) of dynamic memory, leaving 1026 bytes for local variables. Maximum is 2048 bytes.
`
i tried an old version of IDE (1.6.12) but it still get the same error. 
also i tried to ignore that message but i get (No data received) in EZ-GUI app.

**Comment by heisenberg550** [comment]
i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works. 
but could it cause problem later in the project?

**Comment by bharath5673** [comment]
same problem  i get (No data received) in EZ-GUI app. :(((((

**Comment by bharath5673** [comment]
> 
> 
> i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works.
> but could it cause problem later in the project?

can u plz help ... how u fixd it and working?

**Comment by heisenberg550** [comment]
> > i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works.
> > but could it cause problem later in the project?
> 
> can u plz help ... how u fixd it and working?

i just ignored it and robot worked without problem and for (No data received) problem if you sure your baud rate of HC-05 BT module is 115200. i solved it by didn't give the GPS permissions for EZ-GUI app.

**Comment by mahowik** [comment]
> > > i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works.
> > > but could it cause problem later in the project?
> > 
> > 
> > can u plz help ... how u fixd it and working?
> 
> i just ignored it and robot worked without problem and for (No data received) problem if you sure your baud rate of HC-05 BT module is 115200. i solved it by didn't give the GPS permissions for EZ-GUI app.

Hello

yes BT baud rate should be in sync with baud rate specified in config.h
https://github.com/mahowik/BalancingWii/blob/6b93642de00220c7e6bfea96d5a2a1ec307fb43a/config.h#L456

As for the alternative you can try new app created specially for this project:  https://play.google.com/store/apps/details?id=ru.shokurov.mspcontrol

**Comment by bharath5673** [comment]
> 
> 
> > > i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works.
> > > but could it cause problem later in the project?
> > 
> > 
> > can u plz help ... how u fixd it and working?
> 
> i just ignored it and robot worked without problem and for (No data received) problem if you sure your baud rate of HC-05 BT module is 115200. i solved it by didn't give the GPS permissions for EZ-GUI app.

im extremely sorry ,, the problem was with my BT module,,, its was connecting well but TX-RX was not working ... i bought a new BT module and its working awesome :)))           /// lol really took 5/6days to sort it out :(((    ///TYSM for ur response  <3

**Comment by bharath5673** [comment]
> 
> 
> > > > i tried to delete the The section around the erroneous line checks if (chan<8, ) and the code works.
> > > > but could it cause problem later in the project?
> > > 
> > > 
> > > can u plz help ... how u fixd it and working?
> > 
> > 
> > i just ignored it and robot worked without problem and for (No data received) problem if you sure your baud rate of HC-05 BT module is 115200. i solved it by didn't give the GPS permissions for EZ-GUI app.
> 
> Hello
> 
> yes BT baud rate should be in sync with baud rate specified in config.h
> 
> https://github.com/mahowik/BalancingWii/blob/6b93642de00220c7e6bfea96d5a2a1ec307fb43a/config.h#L456
> 
> As for the alternative of EZ-GUI you can try new app created specially for this project: https://play.google.com/store/apps/details?id=ru.shokurov.mspcontrol

TYSM @mahowik  ;)) ,, for this beautiful REPO <3

**Comment by mahowik** [comment]
Your old BT module is also fine i think but you need to sync baud rate of BT module and baud of arduino port. 
Two options:
1) change baud of BT module
2) change baud of arduino port

**Comment by bharath5673** [comment]
> 
> 
> Your old BT module is also fine i think but you need to sync baud rate of BT module and baud of arduino port.
> Two options:
> 
>     1. change baud of BT module
> 
>     2. change baud of arduino port

yup i did it.. its working fine // without out any edits in ur code...

**Comment by satpalsony** [comment]
Now I am busy with some other work, I will definitely take time to try and
thank you very much
