### ISSUE TITLE
No balancing is happening (robot still makes velocity)

### ISSUE THREAD

**Issue by heisenberg550** [mahowik/BalancingWii#19]
Hello sir..
could i have any advice on my robot. No balancing is happening also if i tried to help him to get balancing by hand, It starts velocity on its own.
i didn't change any parameter in code.

this is my PID setting:
![WhatsApp Image 2020-12-23 at 22 54 21](https://user-images.githubusercontent.com/70983368/103141879-0096e200-470c-11eb-9d34-7fe1cdcb7866.jpeg)
and video of robot:
https://user-images.githubusercontent.com/70983368/103141864-bca3dd00-470b-11eb-9d87-32e982c3ad02.mp4

thanks for your help.

**Comment by mahowik** [comment]
1) weels looks too small but you can try to tune PIDs
2) default PIDs are diff https://github.com/mahowik/BalancingWii/blob/6b93642de00220c7e6bfea96d5a2a1ec307fb43a/EEPROM.cpp#L144-L151
3) to reset EEPROM/PIDs google for 'clear EEPROM arduino'    

p.s. Git introduce new feature for talks but not issues https://github.com/mahowik/BalancingWii/discussions
