### ISSUE TITLE
No data received 

### ISSUE THREAD

**Issue by monster211** [mahowik/BalancingWii#21]
Hello, 
I have changed all the necessary information provided in the guid and do the circuit connection properly. But when I run the robot I get “ NO DATA RECEIVED “ warning in the app and there is no enough information in the aux. can you help please ?

**Comment by harshad52** [comment]
Set baudrate 115200,0,0 in AT command mode it worked for me

**Comment by mahowik** [comment]
baud rate should be in sync at:
- config.h
- BT module 
- Android app

Please also read comments on youtube. Most of the cases were answered there.
