### ISSUE TITLE
main_func error 

### ISSUE THREAD

**Issue by ihuzaifa1** [mahowik/BalancingWii#23]
Hello , i hope you are doing well , upon pasting the project in **IDE** i get this error compilation error C:\Users\Huzaifa\AppData\Local\Temp\ccvNRV0F.ltrans0.ltrans.o: In function `main':
C:\Users\Huzaifa\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/main.cpp:43: undefined reference to `setup'
C:\Users\Huzaifa\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/main.cpp:46: undefined reference to `loop'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1 ----->

**Comment by mahowik** [comment]
Hello
Try to use Arduino IDE from year when project was released.

**Comment by ihuzaifa1** [comment]
Thanks i solve this error
