### ISSUE TITLE
No Data Received

### ISSUE THREAD

**Issue by Rishikessh** [mahowik/BalancingWii#24]
baud rate should be in sync at:
- config.h
- BT module 
- Android app

Please also read comments on youtube. Most of the cases were answered there.

_Originally posted by @mahowik in https://github.com/mahowik/BalancingWii/issues/21#issuecomment-875205667_
            

I set the HC-05 module at 115200, and obviously the config is set to 115200. but what do you mean by android app.

Also what forms of troubleshooting can i do to solve this

**Comment by mahowik** [comment]
Android app should have boud rate settings for active BT connection

https://play.google.com/store/apps/details?id=ru.shokurov.mspcontrol

**Comment by Rishikessh** [comment]
Turns out it was just that the TX RX wires were faulty.

thank you mahowik.
