### ISSUE TITLE
How to tune the PID loop?

### ISSUE THREAD

**Issue by josefede** [mahowik/BalancingWii#6]
I have no idea on how to do it, my robot just won't stay upright

**Comment by josefede** [comment]
Btw, what are the predefined PIDs you mention in the readme and how can I use them?

**Comment by josefede** [comment]
I haven't tuned a PID before, so I'm quite lost. I think it would be better if you could explain to me how to make my robot stable. I have managed to calibrate the acc, but I don't know how to continue. Am I missing something?

**Comment by ss1996elcity** [comment]
> I haven't tuned a PID before, so I'm quite lost. I think it would be awesome if you could explain to me how to make my robot stable. I have managed to calibrate the acc, but I don't know how to continue. Am I missing something?

Do you know now haw tune pid in this project?
