### ISSUE TITLE
How do you connect the step motor to the buggy wheel?

### ISSUE THREAD

**Issue by ZeshuiLi** [mahowik/BalancingWii#7]
How do you connect the step motor to the buggy wheel? Can you give us the photo of the connector or the link of the connector.

**Comment by mahowik** [comment]
I found special connector at hobbyking.com
Not sure which one. It was set of years ago...

**Comment by ZeshuiLi** [comment]
Can you tell me the Axle diameter of stepping motors you used and the inner hole diameter of the connector ? Thanks.
