### ISSUE TITLE
Balancingwii.ino doesn't compile

### ISSUE THREAD

**Issue by nicospomer** [mahowik/BalancingWii#9]
Hello,
I'm trying to flash the balancingwii.ino file into my arduino but it doesn't compile. It doesn't contain any instruccions, all lines are comments.

I have followed the instructions provided in another issue but any other file is loaded when .ino is opened.

Could you please explain how should I proceed in order to flash it into the arduino?

Thanks in advance,
Nico

**Comment by mahowik** [comment]
please read online guides how to deal with arduino
